### ISSUE TITLE
Can Krogoth support openssl 1.x.x?

### ISSUE THREAD

**Issue by agilesai1294** [kraj/poky#1]
I am trying to install OpenSSL 1.1.1d using Yocto 2.1. I am getting a compile errors. Can you please help me resolve this?

**Comment by kraj** [comment]
getting openSSL 1.1.x with older versions of yocto is a big undertaking since it is not backward compatible, you have to change dependent packages to use new APIs, I would recommend to upgrade to later yocto versions.
